### ISSUE TITLE
`inspect` on a namespace/option shouldn't call option values that are procs

### ISSUE THREAD

**Issue by kellyredding** [redding/ns-options#49]
This causes problems when the Procs aren't intended to be called.  Maybe it needs to call `returned_value` instead?  Anyway, for inspect purposes, it could just inspect the proc.

**Comment by kellyredding** [comment]
an example backtrace:

```
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/option.rb:30:in `call'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/option.rb:30:in `value'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/namespace.rb:84:in `to_hash'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/namespace.rb:83:in `each'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/namespace.rb:83:in `to_hash'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/namespace.rb:82:in `tap'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/namespace.rb:82:in `to_hash'
ree-1.8.7-2012.02/lib/ruby/gems/gems/ns-options-0.4.1/lib/ns-options/namespace.rb:163:in `inspect'
```

**Comment by kellyredding** [comment]
maybe use a `to_safe_hash` for the inspect??

**Comment by kellyredding** [comment]
The whole problem is that the user may not want the procs to be called.  He might be using a proc as just a proc (not a lazy eval value).

**Comment by kellyredding** [comment]
Ok, disregard.  If the user is writing proc vals they don't want lazy eval'd (called), they need to specify a custom `::Proc` type in the option def.
